name: iOS-ipa-build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      # No need to download CastarSDK as it's already in the repository
      # Just verify it exists
      - name: Verify CastarSDK Framework
        run: |
          if [ -d "ios/Frameworks/CastarSDK.framework" ]; then
            echo "CastarSDK framework found in repository"
          else
            echo "Error: CastarSDK framework not found in ios/Frameworks/"
            exit 1
          fi
          
      - run: flutter pub get
      
      - run: pod repo update
        working-directory: ios

      # This step ensures the framework is properly linked
      - name: Update Podfile for CastarSDK
        run: |
          echo "# Add this line to your Podfile to include CastarSDK framework" >> ios/Podfile
          echo "pod 'CastarSDK', :path => 'Frameworks/CastarSDK.framework'" >> ios/Podfile
        
      - run: flutter build ios --release --no-codesign

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release" 