name: iOS-ipa-build

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
          
      # Verify the framework exists
      - name: Verify CastarSDK Framework
        run: |
          if [ -d "ios/Frameworks/CastarSDK.framework" ]; then
            echo "CastarSDK framework found in repository"
          else
            echo "Error: CastarSDK framework not found in ios/Frameworks/"
            exit 1
          fi
      
      # Create podspec file if it doesn't exist
      - name: Create CastarSDK podspec
        run: |
          if [ ! -f "ios/Frameworks/CastarSDK.podspec" ]; then
            cat > ios/Frameworks/CastarSDK.podspec << EOL
          Pod::Spec.new do |s|
            s.name             = 'CastarSDK'
            s.version          = '1.0.0'
            s.summary          = 'CastarSDK for iOS'
            s.description      = 'CastarSDK for iOS applications'
            s.homepage         = 'https://example.com'
            s.license          = { :type => 'Commercial', :text => 'Proprietary' }
            s.author           = { 'CastarSDK' => 'info@example.com' }
            s.source           = { :path => '.' }
            s.ios.deployment_target = '12.0'
            s.ios.vendored_frameworks = 'CastarSDK.framework'
            s.swift_version = '5.0'
          end
          EOL
            echo "Created CastarSDK.podspec file"
          else
            echo "CastarSDK.podspec file already exists"
          fi
          
      - run: flutter pub get
      
      - run: pod repo update
        working-directory: ios

      - run: flutter build ios --release --no-codesign

      - run: mkdir -p build/ios/iphoneos/Payload
        
      - run: cp -r build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/

      - name: Zip output
        run: cd build/ios/iphoneos && zip -r FlutterIpaExport.ipa Payload

      - name: Upload IPA as artifact
        uses: actions/upload-artifact@v3
        with:
          name: FlutterIpaExport.ipa
          path: build/ios/iphoneos/FlutterIpaExport.ipa

      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "iOS release build" 